### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create new task
POST  http://localhost:3200/tasks
Content-Type: application/json

{
    "title":"Task 1",
    "date":"2022/12/01",
    "description":"testing task",
    "priority":"normal",
    "status":"completed"
}